
name: "Automation: Bork1"
on:
  schedule:
    - cron: 20 13 * * *
  workflow_dispatch: null
  pull_request:
    branches:
        - main
    
jobs:
  run_automation:
    name: "Run Bork1"
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automations/Bork1/requirements.txt
      - name: Run automation
        run: python automations/Bork1/automation.py
