
name: "Automation: prtest3"
on:
  schedule:
    - cron: 00 AM 0 * * *
  workflow_dispatch
  pull_request:
    branches:
        - main
    
jobs:
  run_automation:
    name: "Run prtest3"
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run automation
        run: python automations/prtest3/automation.py
