
name: "Automation: Net Rent"
on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch: null
  pull_request:
    branches:
        - main
    
jobs:
  run_automation:
    name: "Run Net Rent"
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Get the current timestamp
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automations/Net_Rent/requirements.txt
      - name: Run automation
        run: python automations/Net_Rent/automation.py ${{ steps.date.outputs.date }}
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ steps.date.outputs.date }}
          path: automations/Net_Rent/runs/${{ steps.date.outputs.date }}
